# Generated by Django 4.2.6 on 2023-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=30),
        ),
    ]
